SET NAMES 'utf8mb4';
USE umamusume;

DROP FUNCTION IF EXISTS FROM_UNIXTIME_SECONDS;

DELIMITER //

CREATE FUNCTION FROM_UNIXTIME_SECONDS (sec BIGINT)
RETURNS DATETIME
BEGIN
    RETURN DATE_ADD(CAST('1970-01-01' AS DATETIME), INTERVAL sec SECOND);
END //

DELIMITER ;
